### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by 546077311** [ClownpieceStripedAbyss/aya-dance-indexer#1]
PS C:\Users\wcs54\Documents\pypy> .\pypy-cdn-mirror_native_windows-x64.exe
Video path: ./pypydance-song
Proxy: /127.0.0.1:10809
Download delay: 30
Exception in thread "main" java.lang.RuntimeException: java.net.ConnectException
        at moe.kiva.ApiHelper.getHtml(ApiHelper.java:20)
        at moe.kiva.PyPyApi.parse(PyPyApi.java:33)
        at moe.kiva.Main.main(Main.java:74)
        at java.base@21.0.2/java.lang.invoke.LambdaForm$DMH/sa346b79c.invokeStaticInit(LambdaForm$DMH)
Caused by: java.net.ConnectException
        at java.net.http@21.0.2/jdk.internal.net.http.HttpClientImpl.send(HttpClientImpl.java:951)
        at java.net.http@21.0.2/jdk.internal.net.http.HttpClientFacade.send(HttpClientFacade.java:133)
        at moe.kiva.ApiHelper.getHtml(ApiHelper.java:17)
        ... 3 more
Caused by: java.net.ConnectException
        at java.net.http@21.0.2/jdk.internal.net.http.common.Utils.toConnectException(Utils.java:1028)
        at java.net.http@21.0.2/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:227)
        at java.net.http@21.0.2/jdk.internal.net.http.PlainHttpConnection.checkRetryConnect(PlainHttpConnection.java:280)
        at java.net.http@21.0.2/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$2(PlainHttpConnection.java:238)
        at java.base@21.0.2/java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:934)
        at java.base@21.0.2/java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:911)
        at java.base@21.0.2/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base@21.0.2/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
        at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base@21.0.2/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base@21.0.2/java.lang.Thread.runWith(Thread.java:1596)
        at java.base@21.0.2/java.lang.Thread.run(Thread.java:1583)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:833)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:214)
Caused by: java.nio.channels.ClosedChannelException
        at java.base@21.0.2/sun.nio.ch.SocketChannelImpl.ensureOpen(SocketChannelImpl.java:202)
        at java.base@21.0.2/sun.nio.ch.SocketChannelImpl.beginConnect(SocketChannelImpl.java:786)
        at java.base@21.0.2/sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:874)
        at java.net.http@21.0.2/jdk.internal.net.http.PlainHttpConnection.lambda$connectAsync$1(PlainHttpConnection.java:210)
        at java.base@21.0.2/java.security.AccessController.executePrivileged(AccessController.java:114)
        at java.base@21.0.2/java.security.AccessController.doPrivileged(AccessController.java:571)
        at java.net.http@21.0.2/jdk.internal.net.http.PlainHttpConnection.connectAsync(PlainHttpConnection.java:212)
        ... 12 more

**Comment by imkiva** [comment]
Not a bug. 

Make sure your internet connection is active and stable regarding `https://jd.pypy.moe/api/v2/songs`.
Providing `ping` or `curl -vv` logs helps find the root cause.

**Comment by imkiva** [comment]
Just pushed a possible fix https://github.com/ClownpieceStripedAbyss/aya-dance-indexer/commit/b68be877cf5aff6655ea6e64a7a86ce7acc91e12

Would you like to try the newest build from GitHub release and see if it helps?

**Comment by 546077311** [comment]
Thank you. Cleared the hosts
